on:
  push:
    branches: [main]
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

name: release

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: test-package
          # Example: chore(main): release 5.7.0 [skip-ci]
          # ${scope} - parenthesis included, base branch name
          pull-request-title-pattern: 'chore${scope}: release ${version} [skip-ci]'
          pull-request-header: 'Please run the release_notes action before releasing to generate release highlights'
          changelog-path: HISTORY.md
          default-branch: main
